# Generated by Django 3.0.2 on 2020-02-28 16:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Credito',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_pensionado', models.IntegerField(blank=True, null=True)),
                ('capacidad', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('liquido', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('id_plazo', models.IntegerField(blank=True, null=True)),
                ('creado', models.DateTimeField(default=django.utils.timezone.now)),
                ('actualizado', models.DateTimeField(auto_now_add=True)),
                ('estatus_registro', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Deuda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_pensionado', models.IntegerField(blank=True, null=True)),
                ('empresa', models.CharField(blank=True, max_length=100, null=True)),
                ('cantidad_pagos', models.CharField(blank=True, default='0/0', max_length=100)),
                ('cantidad', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('creado', models.DateTimeField(default=django.utils.timezone.now)),
                ('actualizado', models.DateTimeField(auto_now_add=True)),
                ('estatus_registro', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Pensionado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_social', models.CharField(blank=True, max_length=20)),
                ('nombre', models.CharField(blank=True, max_length=100)),
                ('edad', models.IntegerField(blank=True, null=True)),
                ('direccion', models.CharField(blank=True, max_length=200)),
                ('estado', models.CharField(blank=True, max_length=50)),
                ('ciudad', models.CharField(blank=True, max_length=50)),
                ('carta_generada', models.BooleanField(blank=True, default=False)),
                ('sobre_generado', models.BooleanField(blank=True, default=False)),
                ('creado', models.DateTimeField(default=django.utils.timezone.now)),
                ('actualizado', models.DateTimeField(auto_now_add=True)),
                ('estatus_registro', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Plazo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meses_plazo', models.CharField(blank=True, choices=[('1', '24'), ('2', '36'), ('3', '48'), ('4', '60')], default='48', max_length=2, null=True)),
                ('monto_solicitado', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('pago', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('creado', models.DateTimeField(default=django.utils.timezone.now)),
                ('actualizado', models.DateTimeField(auto_now_add=True)),
                ('estatus_registro', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_pensionado', models.CharField(blank=True, max_length=255, null=True)),
                ('reporte', models.FileField(upload_to='documentos/')),
                ('creado', models.DateTimeField(default=django.utils.timezone.now)),
                ('actualizado', models.DateTimeField(auto_now_add=True)),
                ('estatus_registro', models.IntegerField(default=0)),
            ],
        ),
    ]
