# Generated by Django 3.0.2 on 2020-01-28 00:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Credito',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_pensionado', models.IntegerField()),
                ('capacidad', models.DecimalField(decimal_places=2, max_digits=15)),
                ('liquido', models.DecimalField(decimal_places=2, max_digits=15)),
                ('id_plazo', models.IntegerField()),
                ('creado', models.DateTimeField(default=django.utils.timezone.now)),
                ('actualizado', models.DateTimeField(auto_now_add=True)),
                ('estatus_registro', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Deuda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_pensionado', models.IntegerField()),
                ('empresa', models.CharField(max_length=100)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=15)),
                ('creado', models.DateTimeField(default=django.utils.timezone.now)),
                ('actualizado', models.DateTimeField(auto_now_add=True)),
                ('estatus_registro', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Pensionado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_social', models.PositiveIntegerField()),
                ('nombre', models.CharField(max_length=100)),
                ('edad', models.IntegerField()),
                ('direccion', models.CharField(max_length=200)),
                ('estado', models.CharField(max_length=50)),
                ('ciudad', models.CharField(max_length=50)),
                ('creado', models.DateTimeField(default=django.utils.timezone.now)),
                ('actualizado', models.DateTimeField(auto_now_add=True)),
                ('estatus_registro', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Plazo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meses_plazo', models.IntegerField()),
                ('cantidad_a_prestar', models.DecimalField(decimal_places=2, max_digits=15)),
                ('cantidad_pensionado', models.DecimalField(decimal_places=2, max_digits=15)),
                ('creado', models.DateTimeField(default=django.utils.timezone.now)),
                ('actualizado', models.DateTimeField(auto_now_add=True)),
                ('estatus_registro', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_pensionado', models.CharField(blank=True, max_length=255)),
                ('descripcion', models.CharField(max_length=100)),
                ('reporte', models.FileField(upload_to='documentos/')),
                ('creado', models.DateTimeField(default=django.utils.timezone.now)),
                ('actualizado', models.DateTimeField(auto_now_add=True)),
                ('estatus_registro', models.IntegerField(default=0)),
            ],
        ),
    ]
