# Generated by Django 3.0.2 on 2020-02-19 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reporte',
            name='descripcion',
        ),
        migrations.AlterField(
            model_name='pensionado',
            name='numero_social',
            field=models.CharField(max_length=20),
        ),
    ]
