# Generated by Django 3.0.2 on 2020-02-19 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartas', '0002_auto_20200219_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pensionado',
            name='edad',
            field=models.IntegerField(null=True),
        ),
    ]
