# Generated by Django 3.0.2 on 2020-02-19 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartas', '0003_auto_20200219_1316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credito',
            name='id_pensionado',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='credito',
            name='id_plazo',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='reporte',
            name='id_pensionado',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
