# Generated by Django 3.0.2 on 2020-02-20 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartas', '0006_deuda_cantidad_pagos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deuda',
            name='cantidad',
            field=models.DecimalField(decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='deuda',
            name='empresa',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='deuda',
            name='id_pensionado',
            field=models.IntegerField(null=True),
        ),
    ]
