# Generated by Django 3.0.2 on 2020-02-27 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartas', '0009_auto_20200225_1223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plazo',
            name='meses_plazo',
            field=models.CharField(blank=True, choices=[('1', '24'), ('2', '36'), ('3', '48'), ('4', '60')], default='48', max_length=2),
        ),
    ]
